export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const GOOGLE_LOGIN_USER = 'GOOGLE_LOGIN_USER';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
export const ADD_USER_POLLS = 'ADD_USER_POLLS';
export const IS_WAITING = 'IS_WAITING';
export const IS_NOT_WAITING = 'IS_NOT_WAITING';

export const ADD_POLL = 'ADD_POLL';
export const ADD_POLLS = 'ADD_POLLS';
export const ADD_SELECTED_POLL = 'ADD_SELECTED_POLL';
export const ADD_POLL_REQUEST = 'ADD_POLL_REQUEST';
export const DELETE_POLL = 'DELETE_POLL';
export const VOTE = 'VOTE';
